apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    repoURL: http://192.168.42.110:6969/gitlab-instance-02fae04a/hello.git
    path: .
    targetRevision: namespace/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
