apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-wil-deployment
spec:
  selector:
    matchLabels:
      app: app-wil
  replicas: 1
  template:
    metadata:
      labels:
        app: app-wil
    spec:
      containers:
      - name: app-wil
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
kind: Service
apiVersion: v1
metadata:
  name: app-wil-service
spec:
  type: LoadBalancer
  selector:
    app: app-wil
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
