vm:
  base:
    version: "generic/alpine317"
    provider: "virtualbox"
    cpu: 2
    ram: 2048
    hostname: "aartigesS"
  network:
    ip: "192.168.56.110"
    port_guest: 80
    port_host: 8080
  provision:
    shell: "install.sh"
    files_cluster_host: "./k3s_cluster"
    files_cluster_guest: "/home/vagrant/k3s_cluster"

