# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

options = YAML.load_file('config.yml')

if File.exist?('./confs/id_rsa')
  puts "ssh key exist"
else
  system("ssh-keygen -f ./confs/id_rsa -t rsa -N ''")
end

Vagrant.configure("2") do |config|
  config.vm.box = options.fetch('vagrantbox')

  config.vm.provider options.fetch('provider') do |vb|
    vb.cpus = options.fetch('shared').fetch('cpu')
    vb.memory = options.fetch('shared').fetch('ram')
  end

  config.vm.provision "file", source: "./confs", destination: "/home/vagrant/auth"
  config.vm.provision "shell", path: "scripts/provision-base.sh"

  # Server
  config.vm.define options.fetch('server').fetch('hostname') do |server|
    server.vm.hostname = options.fetch('server').fetch('hostname')
    server.vm.network options.fetch('server').fetch('network'), ip: options.fetch('server').fetch('ip')
    
    server.vm.provider options.fetch('provider') do |provider|
      provider.name = options.fetch('server').fetch('hostname')
    end

    server.vm.provision "shell", path: "scripts/provision-server.sh"
  end

  # Worker
  config.vm.define options.fetch('agent').fetch('hostname') do |worker|
    worker.vm.hostname = options.fetch('agent').fetch('hostname')
    worker.vm.network options.fetch('agent').fetch('network'), ip: options.fetch('agent').fetch('ip')
    
    worker.vm.provider options.fetch('provider') do |provider|
      provider.name = options.fetch('agent').fetch('hostname')
    end

    worker.vm.provision "shell", path: "scripts/provision-worker.sh"
  end
end
